// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Session struct {
	ID           string
	UserID       string
	Email        string
	RefreshToken string
	AccessToken  string
	Provider     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID            string
	Email         string
	Sub           string
	Name          string
	EmailVerified bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
