// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, hashed_ip, created_at, updated_at 
)
VALUES (
  ?, ?, ?, ?
)
RETURNING id, hashed_ip, created_at, updated_at
`

type CreateUserParams struct {
	ID        string
	HashedIp  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.HashedIp,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HashedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
