name: ci

on:
  pull_request:
    branches: [main]

env:
  GO_VERSION: '1.24'
  TEMPL_VERSION: 'v0.3.906'

jobs:
  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@${{ env.TEMPL_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Templ generate
        run: templ generate

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Run staticcheck
        run: staticcheck ./...

  security:
    name: security
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@${{ env.TEMPL_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Templ generate
        run: templ generate

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec -exclude-generated ./...

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@${{ env.TEMPL_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Templ generate
        run: templ generate

      - name: Run tests
        run: go test ./...
